### PR TITLE
Add note about configurator not working when having profile lists

### PR DESCRIPTION
**Pull request by GeorgianaElena**
There is still confusion around this with the communities: https://2i2c.freshdesk.com/a/tickets/1233

----
📚 Documentation preview 📚: https://2i2c-pilot-documentation--204.org.readthedocs.build/en/204/

### CODE REVIEW

**Comment by GeorgianaElena** [comment]
Wondering if this should be ported over to https://github.com/2i2c-org/community-showcase ?

**Comment by GeorgianaElena** [comment]
Hmm, I don't seem to be able to request a review from  @jnywong 🤔

**Comment by sgibson91** [comment]
Screenshot 2024-01-11 at 17 01 05

She is probably not a member of a team that has the appropriate access to this repo to have her review requested. If there's a partnerships team, or some other appropriate team, it should probably be added.

**Comment by damianavila** [comment]
> She is probably not a member of a team that has the appropriate access to this repo to have her review requested. If there's a partnerships team, or some other appropriate team, it should probably be added.

I just checked and Partnership was added, so I requested a review from @jnywong.

**Review by jnywong — APPROVED** [review]

**Comment by GeorgianaElena** [comment]
Thank you all!

**Pull request merged**
